# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/942e10f7-aa81-4cbf-8f0e-e5572aa93eca";
      fsType = "btrfs";
      options = [ "subvol=@rootnix" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/efb91f16-598e-4785-9f8d-bd98766f6437";
  boot.initrd.luks.devices."cryptswap".device = "/dev/nvme0n1p6";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/942e10f7-aa81-4cbf-8f0e-e5572aa93eca";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/942e10f7-aa81-4cbf-8f0e-e5572aa93eca";
      fsType = "btrfs";
      options = [ "subvol=@boot" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/E86A-755D";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/mapper/cryptswap"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
