# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "firewire_ohci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fbc4ac84-c70c-459f-9ad3-707f7eb6a853";
      fsType = "btrfs";
      options = [ "subvol=@rootnix" ];
    };


  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/ba053df3-424d-4c9d-9636-eeccd0e2150e";
  boot.initrd.luks.devices."cryptswap".device = "/dev/disk/by-uuid/75bab479-fb98-4b5e-8180-2894fc9cdeb5";
  
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/fbc4ac84-c70c-459f-9ad3-707f7eb6a853";
      fsType = "btrfs";
      options = [ "subvol=@boot" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fbc4ac84-c70c-459f-9ad3-707f7eb6a853";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/B769-53B8";
      fsType = "vfat";
    };
  
  fileSystems."/tmp" =
    { fsType = "tmpfs"; };

  swapDevices = [ { device = "/dev/mapper/cryptswap"; } ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # High-DPI console
  console.font = lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
}
