# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "firewire_ohci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/030453bc-b17c-4c3a-86ef-1b2b4c3b0cdb";
      fsType = "btrfs";
      options = [ "subvol=@rootnix" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/755d2b04-5d3c-4865-b0d1-7f01c9301dac";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/030453bc-b17c-4c3a-86ef-1b2b4c3b0cdb";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/9BD8-9601";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/aa12efb4-a2fd-41e1-9dd7-ca42c51c21c3"; }
    ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
